on:
  workflow_dispatch:

name: Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        dnf -y install docker
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: palette.flatpak
        manifest-path: de.home_ui.cli.yml
        arch: ${{ matrix.arch }}